# Generated by Django 3.0.5 on 2020-04-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeno', '0002_auto_20200430_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='zenoitem',
            name='zenoid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zenoitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
