# Generated by Django 3.0.5 on 2020-04-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeno', '0003_auto_20200430_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='zenoitem',
            name='client_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
